### ISSUE TITLE
Final project

### ISSUE THREAD

**Issue by marina-cyber** [MartyanovVV/TimeS#10]
1.  Почему finally , а не final ?

3.  Или странная отрисовка всех компонентов временного ряда, но я не вижу там трендов. Откуда взялась не стационарность? По каким характеристикам они не стационарны?

4. В классических моделях вы фактически предсказывали только один ряд, то есть рассматривали немультипликативные ряды. Нужно использовать модели для мульвариативных рядов (те же VAR, VARMA модели). И не забыть предварительно проверить причинность рядов по Грейднжеру. 

5. Нужно объяснить, какие значения для метрик вы считаете супер, какие нормально, какие - плохо. Или определите интервалы для значений метрик, но в любом случае надо объяснить. Пока вот такой анализ не понятен:
SMAPE: 0.22 - нормально
RMSE: 187 - плохо
MAE: 140 - нормально
MAPE: 38 - плохо
R2: 0.96 - хорошо

6.  Надо настроить LSTM и GRU так, чтобы их метрики были лучше, или хотя бы сравнимы с классическими моделями. Добавляйте новые блоки, поиграйтесь с параметрами, и т.д.

7. Не надо обучать бешенное кол-во эпох, тем более это не гарантия, что вы получаете лучший вариант обучения.
100 эпох вполне достаточно. Может даже меньше - можно посмотреть на кросс валидации, на какой эпохе логлосс на трейне пересечет логлосс на тесте и потом превысит его.

**Comment by MartyanovVV** [comment]
Посмотрите пожалуйста модели, я старался переучивать, подобрал параметры но типо все по максимуму выжал.
Графики автокорреляций и составляющих временных рядов не показал, тк гит дает ограничение на 25 мб а с ними файл весил 27.
Итоги еще не писал.

**Comment by marina-cyber** [comment]
Я правильно поняла, что нейронки вы обучаете не на мультивариативном временном ряду, а вытаскиваете оттуда одну ветку?

**Comment by MartyanovVV** [comment]
lstm и TCN да, GRU учится на всех столбцах

**Comment by marina-cyber** [comment]
Lstm и tcn тоже должны учиться на более, чем 2х рядах.

⁣Получить BlueMail для Android ​

На 11 янв. 2024 г., 00:11, в 00:11, MartyanovVV ***@***.***> написал:п>lstm и TCN да, GRU учится на всех столбцах

**Comment by MartyanovVV** [comment]
Только их исправить?

**Comment by marina-cyber** [comment]
Да, остальное почти норм.

**Comment by MartyanovVV** [comment]
Исправил

**Comment by marina-cyber** [comment]
проведите тест на причинность, откиньте все ряды, которые непричинные с целевым. И давайте вы попробуете увеличить число сеплов для обучения и нормально обучить lstm и gru.

И давайте уже заканчивать с этим проектом.

**Comment by marina-cyber** [comment]
Работа засчитана.
